nelmio_api_doc:
    documentation:
        info:
            title: Books Application
            description: Books Application api
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/auth/email/permission-test$)
